### ISSUE TITLE
blocking DataBoard copy and = c'tor

### ISSUE THREAD

**Issue by TianaLeykin** [RonnySivan/AdvancedProgramming_Ex3#1]
I blocked copy and assignment of DataBoard
 http://moodle.tau.ac.il/mod/forum/discuss.php?d=61791

If they put the updated header- we'll replace it
otherwise,  we'll need to remove the code I added when we're done

**Comment by sapirbenor** [comment]
The classes which implement DataBoard and IBattleshipGameAlgo block them.
